### ISSUE TITLE
请问能否做一个像微信插件一样的快捷回复和气泡功能

### ISSUE THREAD

**Issue by mdogwoop** [ichenhe/QQ-Notify-Evolution#13]

**Comment by liangchenhe55** [comment]
正有此意，不过... 暂时没时间。

**Comment by Clansty** [comment]
我刚刚试了一下，发现我做不起来

（（我不熟悉安卓开发qwq

**Comment by ichenhe** [comment]
我重新思考了一下，决定不做了。原因如下：

- QQ无法实现回复。微信借用的是 Android Auto 接口实现，但是 QQ 本身就没有适配这个接口。
- 在无法实现回复的情况下，气泡没有什么意义。

如果谁有进一步的理由觉得应该做，或者其他可行方案，欢迎提出。

**Comment by Clansty** [comment]
> 在无法实现回复的情况下，气泡没有什么意义。

气泡似乎不需要依赖回复，只需要 Activity 是可嵌入的并且是可调节大小的

**Comment by ichenhe** [comment]
@Clansty 我没有说依赖回复。只是说如果不能支持回复，那么气泡就没有什么意义。难道只是为了保留历史记录吗，而且还只是单向的，不完整的记录。（无法获取自己发送的内容，也无法获取应用内接收的消息）

**Comment by Clansty** [comment]
不是这样的，气泡点开之后是嵌入的 QQ 界面，不是我们自己做的界面。可以参考 telegram

**Comment by ichenhe** [comment]
@Clansty 这么做的前提是 qq 的 activity 对这种场景做了适配。如果没有（比如微信），那就我就得自己实现一个（微信插件就是这么做的）。于是就有了前面所述的问题。

显然，qq 没有适配。通知气泡要求 activity 必须是 `android:allowEmbedded`
