### ISSUE TITLE
还会更新嘛

### ISSUE THREAD

**Issue by Agoines** [ichenhe/QQ-Notify-Evolution#14]
悄声问一句，这个项目还会继续更新下去嘛🥺

**Comment by liangchenhe55** [comment]
会呀。只不过当初做这个项目为了的那个人现在不在了，所以目前看到源代码依然会很难受。
不过我不想逃避，只有当可以平静面对这些东西的时候，才是真的放下了，对吧 (^ ^)

**Comment by Agoines** [comment]
> 会呀。只不过当初做这个项目为了的那个人现在不在了，所以目前看到源代码依然会很难受。
> 不过我不想逃避，只有当可以平静面对这些东西的时候，才是真的放下了，对吧 (^ ^)

这样啊，蹲一波，如果有ui的想法可以滴滴我啊（）

**Comment by ichenhe** [comment]
更新了嗷 ε٩(๑> ₃ <)7з

**Comment by Agoines** [comment]
> 
好哎,,Ծ^Ծ,,
