### ISSUE TITLE
能不能适配一下QQ国际版

### ISSUE THREAD

**Issue by ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh** [ichenhe/QQ-Notify-Evolution#17]
QQ国际版通知无法在顶部预览,想用这个代替一下

**Comment by liangchenhe55** [comment]
据我所知 QQ 国际版官方已经不维护了。Play 上也只有 QQ 标准版（虽然比大陆版精简了一点，但是包名是一样的）

所以不会加入国际版的适配。
