### ISSUE TITLE
内源模式无法正常使用

### ISSUE THREAD

**Issue by PianCat** [ichenhe/QQ-Notify-Evolution#18]
机型：OnePlus 7 Pro（OxygenOS 11）
安卓版本：Android 11
女娲石版本：6.3-dev
QQ通知进化版本：2.2.1

具体表现为：
Nevo开启内源模式后并没有对QQ的通知进行正确接管，而是使用了QQ自己的通知通道

**Comment by yFFyF** [comment]
6.2应该是直接不显示通知 一直都有问题

**Comment by Neubulae** [comment]
同

**Comment by yFFyF** [comment]
> 同

直接改notification_policy.xml 只知道这个笨办法

**Comment by ichenhe** [comment]
你们是从哪搞得 Nevo 6.3

我这边 Nevo 6.2 内源模式/adb模式 都工作正常，也可以自动清除通知。

**Comment by entr0pia** [comment]
> 你们是从哪搞得 Nevo 6.3
> 
> 我这边 Nevo 6.2 内源模式/adb模式 都工作正常，也可以自动清除通知。

Telegram 群组 [Oasis 的时光杂货店](https://t.me/joinchat/isfzySd_f3MyNDk1)

**Comment by STTecCEO** [comment]
> > > > 同
> > > 
> > > 
> > > 直接改notification_policy.xml 只知道这个笨办法
> > 
> > 
> > 具体是？
> > 似乎现在没问题了，重新装了一次QQ。但是女娲石仍然没法正常地移除通知
> 
> /data/system/notification_policy.xml

具体是怎么改呢大佬指点一下🥲

**Comment by yFFyF** [comment]
> > > > > 同
> > > > 
> > > > 
> > > > 直接改notification_policy.xml 只知道这个笨办法
> > > 
> > > 
> > > 具体是？
> > > 似乎现在没问题了，重新装了一次QQ。但是女娲石仍然没法正常地移除通知
> > 
> > 
> > /data/system/notification_policy.xml
> 
> 具体是怎么改呢大佬指点一下🥲

打开开发者模式 显示通知渠道警告, 会提示channel id 你就照葫芦画瓢加呗🫠

**Comment by yFFyF** [comment]
@ichenhe 现在qq接了华为推送 HwPushChannelID 这个channel的通知不处理, 考不考虑更新一下呀

**Comment by ichenhe** [comment]
> @ichenhe 现在qq接了华为推送 HwPushChannelID 这个channel的通知不处理, 考不考虑更新一下呀

@yFFyF No. See #29

**Comment by STTecCEO** [comment]
> > > > > > 同
> > > > > 
> > > > > 
> > > > > 直接改notification_policy.xml 只知道这个笨办法
> > > > 
> > > > 
> > > > 具体是？
> > > > 似乎现在没问题了，重新装了一次QQ。但是女娲石仍然没法正常地移除通知
> > > 
> > > 
> > > /data/system/notification_policy.xml
> > 
> > 
> > 具体是怎么改呢大佬指点一下🥲
> 
> 打开开发者模式 显示通知渠道警告, 会提示channel id 你就照葫芦画瓢加呗🫠

![Screenshot_20221013-011132](https://user-images.githubusercontent.com/35169436/195406280-8f153900-9aab-4281-9ecd-96d861a5f522.png)
是这样加嘛...保存完会过一会儿就消失了...
