### ISSUE TITLE
2.2.3版本消息通知不能显示在对话部分

### ISSUE THREAD

**Issue by xyf2018** [ichenhe/QQ-Notify-Evolution#22]
类原生Pixel Experience，安卓版本11，QQ版本Play商店版8.2.11
**传统**工作模式下，经过处理的消息通知显示在了通知栏的“通知”部分，而不是“对话”部分
图1是显示在“通知”部分的2.2.3版本的截图
图2是显示在“对话”部分的2.2.0版本的截图
![Screenshot_20210922-171341_Pixel_启动器](https://user-images.githubusercontent.com/33438484/134318342-fd939ea6-1dbb-4e8e-8d1e-f7a8986f0688.png)
![Screenshot_20210922-171441_Pixel_启动器](https://user-images.githubusercontent.com/33438484/134318391-16340073-1f5c-4259-a5a4-89187956d653.png)

**Comment by ichenhe** [comment]
Nevo 模式下是正常的？

**Comment by xyf2018** [comment]
是的，Nevo模式下可以正常显示在对话部分
