### ISSUE TITLE
经过华为推送的qq消息不会被接管

### ISSUE THREAD

**Issue by ruomuyi** [ichenhe/QQ-Notify-Evolution#24]
自从qq消息接入hms推送以后，凡是经过hms推送的消息都不会被通知进化接管（传统工作模式）

**Comment by ichenhe** [comment]
系统推送的原理和QQ不一样。其通知来源是系统发出的，而不是QQ。

鉴于我非常讨厌华为，这个问题目前不会修复。
讨厌华为的原因看这里：https://wg.chenhe.me/zh/announcement/huawei/
