### ISSUE TITLE
Conversations features (对话泡) support

### ISSUE THREAD

**Issue by Flyfish233** [ichenhe/QQ-Notify-Evolution#26]
`女娲石不支持对话功能`

**Comment by ichenhe** [comment]
无法实现。原因如下：

1. QQ Nevo 利用通知栏获得新消息，因此对于 QQ 处于前台的情况，插件是拿不到消息内容的。那么就会出现内容缺失，回话气泡会显得很奇怪。
2.  QQ Nevo 不支持回复功能，实现会话气泡意义不大。

微信的女娲石插件利用微信的 Android auto 接口拿到了消息内容并实现回复，qq 没有这个接口。
另外最新版微信也取消了，所以女娲石插件其实已经无法继续使用。

**Comment by Rove24** [comment]
最新版的8.0.50微信可以通过6.2女娲石和微信替身实现对话泡回复，大佬有没有办法可以实现QQ的对话泡回复呢
