### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [ichenhe/QQ-Notify-Evolution#30]
请问可以发布到 F-Droid 吗？

**Comment by ichenhe** [comment]
F-Droid 对 app 的依赖也有要求，而且需要可信构建。比较麻烦，我可以试试看

**Comment by linsui** [comment]
应用的依赖很少，都是开源的，没什么问题。唯一一个是 version name 和 version code 是动态生成的，F-Droid 用正则获取版本信息，所以没法自动更新。如果你同意，我可以帮助打包提交。

**Comment by ichenhe** [comment]
可以。同意。
在 2022年8月11日+0800 19:40，linsui ***@***.***>，写道：

**Comment by linsui** [comment]
MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11541

我可以在这个仓库里添加 fastlane 文件吗？F-Droid 会从这里抓取应用描述。如果可以，我开个合并请求。自动更新的问题要怎么解决？不自动更新还是在哪里发布version code？

**Comment by ichenhe** [comment]
恩。添加需要的文件开 pr 吧。版本号写死在 gradle 里就行，以后发版手动更新。
在 2022年8月11日+0800 20:37，linsui ***@***.***>，写道：

**Comment by linsui** [comment]
好的，稍后 PR。

**Comment by linsui** [comment]
3.0.0 的 apk 版本是 UNKNOWN，版本号是 1，看起来是因为 https://github.com/ichenhe/QQ-Notify-Evolution/blob/master/.github/workflows/release.yml#L62 这里 appVersion 是在构建 apk 之后才运行。可以修一下重新上传 apk 吗？
