### ISSUE TITLE
偶尔无法跳转到QQ

### ISSUE THREAD

**Issue by Jason-Fly** [ichenhe/QQ-Notify-Evolution#4]
已开无障碍，已取消电池优化，已按最佳实践设置，三星Oneui1.0韩版。尤其是在收到消息10分钟后再点击时，无法跳转。需要进入一次QQ才行，否则之后的消息更加无法跳转。不知道我是不是个例T.T
QQ版本是play版7.7.6

**Comment by liangchenhe55** [comment]
似乎因为 QQ 的 pending intent 在某些条件下会失效。
而最新的 Android 版本已经不再允许通过反射拿到具体的 intent 了。

得想想有没有好办法

**Comment by Jason-Fly** [comment]
目前我的办法是，频繁QQ的时候，就把它锁在后台不划掉，就都能跳转了。

**Comment by liangchenhe55** [comment]
感谢您的建议。 经网友提醒 在源项目没有放置开源协议的情况下默认不允许修改分发。因此现在将此仓库转为私有 并下架所有已发布的应用。在此对原作者致歉。

**Comment by ichenhe** [comment]
现在应该已经没有这个问题了。

从源头去掉了始作俑者。
